terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
    }
  }
}

data "aws_rds_engine_version" "mysql" {
  engine  = "mysql"
  version = "8.0"
  latest  = true
}

resource "random_password" "db" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+"
}

resource "random_password" "redis" {
  length  = 32
  special = true
  # ElastiCache rejects @, ", and /. Keep the set small so .env quoting stays safe.
  override_special = "!&#^<>-"
}

resource "aws_db_subnet_group" "this" {
  name        = var.name
  description = "Private subnets for ${var.name}"
  subnet_ids  = var.private_subnet_ids
}

resource "aws_db_parameter_group" "this" {
  name        = "${var.name}-mysql8"
  family      = "mysql8.0"
  description = "utf8mb4 for ${var.name}"

  parameter {
    name         = "character_set_server"
    value        = "utf8mb4"
    apply_method = "pending-reboot"
  }

  parameter {
    name         = "collation_server"
    value        = "utf8mb4_unicode_ci"
    apply_method = "pending-reboot"
  }
}

resource "aws_db_instance" "this" {
  identifier = var.name

  engine         = "mysql"
  engine_version = data.aws_rds_engine_version.mysql.version
  instance_class = var.db_instance_class

  db_name  = "truckit_mcp"
  username = "mcp"
  password = random_password.db.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  parameter_group_name   = aws_db_parameter_group.this.name
  vpc_security_group_ids = [var.rds_sg_id]

  allocated_storage          = 20
  storage_type               = "gp3"
  storage_encrypted          = true
  multi_az                   = false
  publicly_accessible        = false
  backup_retention_period    = var.db_backup_retention_days
  skip_final_snapshot        = true
  deletion_protection        = false
  delete_automated_backups   = true
  copy_tags_to_snapshot      = true
  apply_immediately          = true
  auto_minor_version_upgrade = true

  tags = {
    Name = var.name
  }
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "/truckit-mcp/${var.env}/db"
  description             = "MySQL credentials generated by Terraform. Do not rotate in the console; RDS keeps this password."
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id
  secret_string = jsonencode({
    username = aws_db_instance.this.username
    password = random_password.db.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
    dbname   = aws_db_instance.this.db_name
    engine   = "mysql"
  })
}

resource "aws_elasticache_subnet_group" "this" {
  name        = var.name
  description = "Private subnets for ${var.name}"
  subnet_ids  = var.private_subnet_ids
}

resource "aws_elasticache_replication_group" "this" {
  replication_group_id = var.name
  description          = "Truckit MCP Redis"

  engine         = "redis"
  engine_version = var.redis_engine_version
  node_type      = var.redis_node_type
  port           = 6379

  # AUTH and in-transit encryption require a replication group. One node, no failover.
  num_cache_clusters         = 1
  automatic_failover_enabled = false
  multi_az_enabled           = false

  parameter_group_name = "default.redis7"
  subnet_group_name    = aws_elasticache_subnet_group.this.name
  security_group_ids   = [var.redis_sg_id]

  at_rest_encryption_enabled = true
  transit_encryption_enabled = true
  auth_token                 = random_password.redis.result
  snapshot_retention_limit   = 0
  apply_immediately          = true

  tags = {
    Name = var.name
  }
}

resource "aws_secretsmanager_secret" "redis" {
  name                    = "/truckit-mcp/${var.env}/redis"
  description             = "Redis AUTH token and endpoint. The app must use REDIS_SCHEME=tls."
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "redis" {
  secret_id = aws_secretsmanager_secret.redis.id
  secret_string = jsonencode({
    host       = aws_elasticache_replication_group.this.primary_endpoint_address
    port       = aws_elasticache_replication_group.this.port
    auth_token = random_password.redis.result
    tls        = true
  })
}
